### ISSUE TITLE
Crash on trading with NPCs 

### ISSUE THREAD

**Issue by ujjman** [Terasology/MetalRenegades#176]
while playing MR, if we interact (using `E`) with any citizen (like `badCitizen`), and click on `Show me what you've got` and after that select any item (eg. torches, dynamite etc.) then as soon as we click on `Trade` button, a NPE occurs 

Steps to reproduce -
1. Start game with MR template
2. Interact with any NPC (using `E`)
3. Click on `Show me what you've got` in the dialog window
4. Select any item in the list
5. Click on `Trade` and NPE will occur

![e6](https://user-images.githubusercontent.com/49057926/143691868-15977ec9-60b8-4c1d-88df-daf033e7ca74.png)

https://user-images.githubusercontent.com/49057926/143691872-e4b00042-b9c2-4427-84dd-3f66c2968143.mp4

**Comment by jdrueckert** [comment]
My current guess is, that this happens because we do not check whether one item per list (trader-side and player-side) has been selected when executing the action resulting from clicking the "Trade" button.
When trying to get the selections of the two lists in https://github.com/Terasology/MetalRenegades/blob/cac50b8647beddd3e1c8f44638e121653caf8f54/src/main/java/org/terasology/metalrenegades/economy/ui/TradingScreen.java#L115, we will receive `null` for the one in which no selection was made and, thus, run into the NPE.
